name: Deploy Frontend to EC2

on:
  push:
    branches:
      - dev  # 또는 배포하고 싶은 다른 브랜치 이름

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Create known_hosts file if not exists
      run: |
        if [ ! -f ~/.ssh/known_hosts ]; then
          touch ~/.ssh/known_hosts
        fi

    - name: Add SSH key to known hosts
      run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/authorized_keys

    - name: Copy frontend files to EC2
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./fe/ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/paypick

    - name: Install dependencies and restart application
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/paypick
          npm install
          npm run build
          pm2 restart next-app || pm2 start npm --name "next-app" -- start
        EOF
